---
Name: iqbigcommerce
---
SilverStripe\Admin\LeftAndMain:
  frame_options: false
UncleCheese\Dropzone\FileAttachmentField:
  track_files: true
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.bcCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "bcCache"
IQnection\BigCommerceApp\Cron\BackgroundJobs:
  recurring_jobs:
    'sync_categories':
      'call_class': 'IQnection\BigCommerceApp\Cron\SyncCategories'
      'call_method': 'run'
      'hours': 0
    'sync_products':
      'call_class': 'IQnection\BigCommerceApp\Cron\SyncProducts'
      'call_method': 'run'
      'hours': 1
    'background_job_cleaner':
      'call_class': 'IQnection\BigCommerceApp\Cron\BackgroundJobs'
      'call_method': 'clean'
      'hours': 2
IQnection\BigCommerceApp\Control\Listener:
  registry:
    'store/category/*':
      - 'IQnection\BigCommerceApp\Model\Category::processWebhook'
    'store/product/*':
      - 'IQnection\BigCommerceApp\Model\Product::processWebhook'
